# Generated by Django 4.0 on 2021-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('content', models.TextField(blank=True, db_column='content')),
                ('create_at', models.DateTimeField(db_column='create_at', default=None)),
                ('update_at', models.DateTimeField(blank=True, db_column='update_at', default=None, null=True)),
            ],
        ),
    ]
