version: '3'

services:
  python3:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../.:/code
    environment:
      PYTHONPATH: /code
      LANGUAGE: "${LANGUAGE}"
      TIMEZONE: "${TIMEZONE}"
    ports:
      - "8000:8000"